# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [ ]:
### importing numpy as np
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [5]:
### printing numpy version
print("Using Numpy version", np.__version__)
print(np.show_config())


Using Numpy version 2.4.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-bdy1jcl0/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-bdy1jcl0/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-bdy1jcl0/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-bdy1jcl0/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    o

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [51]:
### different ways to generate 2x3x5 array with random values

a = np.random.random((2, 3, 5))

a = np.empty([2, 3, 5])

a = np.random.randint(100, size=(2, 3, 5)) # (block, rows, columns)








### 4. Print a.


In [21]:
### [your code here]
print(a)

[[[0.4260072  0.54244104 0.84076597 0.72274971 0.04942083]
  [0.84339427 0.2151064  0.04252151 0.24941223 0.12844605]
  [0.22903178 0.47687166 0.68764999 0.80551995 0.91955437]]

 [[0.75589799 0.60157359 0.52841819 0.19262276 0.09928329]
  [0.4279829  0.50125799 0.20061067 0.50142755 0.70656605]
  [0.79898602 0.54136294 0.47504946 0.37544134 0.09156005]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [43]:
### create a 5x2x3 array with all values 1
b = np.ones((5, 3, 2))



### 6. Print b.


In [44]:
### [your code here]
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [45]:
### Check if arrays a and b have the same size
try:
    test_equal = (a == b)
except:
    print("The two arrays cannot be compared since they are not of the same size")



The two arrays cannot be compared since they are not of the same size



### 8. Are you able to add a and b? Why or why not?


In [46]:
### Check addition for the arrays
try:
    a + b
except:
    print("Addition of the arrays is not possible since they are of different sizes")


Addition of the arrays is not possible since they are of different sizes




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [47]:
### performing c = b'
c = np.transpose(b)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [53]:
### performing a + c, since they are of the same size now
d = a + c



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [65]:
### your code
print(a)
print(d)



[[[44  7 63 43 40]
  [18 82 16 91 76]
  [73 65 66 74 43]]

 [[31 49 43 65 38]
  [80 86 55 57  1]
  [46  4 36 19 42]]]
[[[45.  8. 64. 44. 41.]
  [19. 83. 17. 92. 77.]
  [74. 66. 67. 75. 44.]]

 [[32. 50. 44. 66. 39.]
  [81. 87. 56. 58.  2.]
  [47.  5. 37. 20. 43.]]]



### 12. Multiply a and c. Assign the result to e.


In [59]:
### [your code here]

e = a * c
print(e)


[[[44.  7. 63. 43. 40.]
  [18. 82. 16. 91. 76.]
  [73. 65. 66. 74. 43.]]

 [[31. 49. 43. 65. 38.]
  [80. 86. 55. 57.  1.]
  [46.  4. 36. 19. 42.]]]




### 13. Does e equal to a? Why or why not?


In [61]:
### e == a, since a * c(c is a unity matrix) = a
test_multiplication = (e == a)
print(test_multiplication)


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [64]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)


92.0 2.0 49.43333333333333



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [106]:
### [your code here]
f = np.empty((2, 3, 5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [107]:
### [your code here]
f = np.select(
    [d == d_min, d < d_mean, d == d_mean, d < d_max, d == d_max],
    [0, 25, 50, 75, 100],
    default=f
)






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [108]:
### [your code here]
print(d)
print(f)

[[[45.  8. 64. 44. 41.]
  [19. 83. 17. 92. 77.]
  [74. 66. 67. 75. 44.]]

 [[32. 50. 44. 66. 39.]
  [81. 87. 56. 58.  2.]
  [47.  5. 37. 20. 43.]]]
[[[ 25.  25.  75.  25.  25.]
  [ 25.  75.  25. 100.  75.]
  [ 75.  75.  75.  75.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  75.   0.]
  [ 25.  25.  25.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [112]:
### [your code here]
mapping = {0: 'A', 25: 'B', 50: 'C', 75: 'D', 100: 'E'}
print(f)

labels = [
    [[mapping[val] for val in row] for row in plane]
    for plane in f
]

print(labels)

[[[ 25.  25.  75.  25.  25.]
  [ 25.  75.  25. 100.  75.]
  [ 75.  75.  75.  75.  25.]]

 [[ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  75.   0.]
  [ 25.  25.  25.  25.  25.]]]
[[['B', 'B', 'D', 'B', 'B'], ['B', 'D', 'B', 'E', 'D'], ['D', 'D', 'D', 'D', 'B']], [['B', 'D', 'B', 'D', 'B'], ['D', 'D', 'D', 'D', 'A'], ['B', 'B', 'B', 'B', 'B']]]
